name: build and deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Image Tag
        id: set_image_tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
        # We store the SHA in an environment variable for easier re-use

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Push both the specific SHA tag and the 'latest' tag
          tags: |
            remiscus/voiceiq-backend:${{ env.IMAGE_TAG }}
            remiscus/voiceiq-backend:latest

      - name: Verify push (Optional, for debugging)
        run: docker pull remiscus/voiceiq-backend:${{ env.IMAGE_TAG }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Connection successful!"
            # Stop the existing container if it's running
            sudo docker stop voiceiq-backend || true
            # Remove the existing container if it exists
            sudo docker rm voiceiq-backend || true
            # Pull the image using the unique SHA tag
            sudo docker pull remiscus/voiceiq-backend:${{ env.IMAGE_TAG }}
            # Run the new container with environment variables, using the unique SHA tag
            sudo docker run -d --name voiceiq-backend -p 8000:8000 \
              -e GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" \
              -e SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
              -e SUPABASE_KEY="${{ secrets.SUPABASE_KEY }}" \
              -e LOGFIRE_WRITE_TOKEN="${{ secrets.LOGFIRE_WRITE_TOKEN }}" \
              remiscus/voiceiq-backend:${{ env.IMAGE_TAG }}